name: Build and Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o ./publish
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: portfolio-build
        path: ./publish

  # Optional: Deploy to Azure Web App (if you have one)
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - uses: actions/checkout@v4
  #   
  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: portfolio-build
  #       path: ./publish
  #   
  #   - name: Deploy to Azure Web App
  #     uses: azure/webapps-deploy@v3
  #     with:
  #       app-name: 'your-portfolio-app-name'
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #       package: ./publish 